/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Specs {
  'weight' : bigint,
  'model' : string,
  'year' : bigint,
  'acceleration' : number,
  'power' : bigint,
  'topSpeed' : bigint,
  'engine' : string,
}
export interface Vehicle {
  'id' : bigint,
  'vehicleType' : string,
  'make' : string,
  'specs' : Specs,
  'nanosecondsCreated' : bigint,
  'price' : bigint,
  'images' : Array<string>,
}
export interface _SERVICE {
  'addVehicle' : ActorMethod<
    [string, string, Specs, bigint, Array<string>],
    bigint
  >,
  'getAllVehicles' : ActorMethod<[], Array<Vehicle>>,
  'getMapSizes' : ActorMethod<[], [bigint, bigint]>,
  'getUserFavorites' : ActorMethod<[Principal], Array<bigint>>,
  'getVehicleById' : ActorMethod<[bigint], Vehicle>,
  'getVehiclesByType' : ActorMethod<[string], Array<Vehicle>>,
  'isFavorite' : ActorMethod<[bigint], boolean>,
  'isRegistered' : ActorMethod<[], boolean>,
  'toggleFavorite' : ActorMethod<[bigint], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];