/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Specs = IDL.Record({
  'weight' : IDL.Nat,
  'model' : IDL.Text,
  'year' : IDL.Nat,
  'acceleration' : IDL.Float64,
  'power' : IDL.Nat,
  'topSpeed' : IDL.Nat,
  'engine' : IDL.Text,
});
export const Vehicle = IDL.Record({
  'id' : IDL.Nat,
  'vehicleType' : IDL.Text,
  'make' : IDL.Text,
  'specs' : Specs,
  'nanosecondsCreated' : IDL.Int,
  'price' : IDL.Int,
  'images' : IDL.Vec(IDL.Text),
});

export const idlService = IDL.Service({
  'addVehicle' : IDL.Func(
      [IDL.Text, IDL.Text, Specs, IDL.Int, IDL.Vec(IDL.Text)],
      [IDL.Nat],
      [],
    ),
  'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
  'getMapSizes' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
  'getUserFavorites' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Nat)], ['query']),
  'getVehicleById' : IDL.Func([IDL.Nat], [Vehicle], ['query']),
  'getVehiclesByType' : IDL.Func([IDL.Text], [IDL.Vec(Vehicle)], ['query']),
  'isFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
  'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Specs = IDL.Record({
    'weight' : IDL.Nat,
    'model' : IDL.Text,
    'year' : IDL.Nat,
    'acceleration' : IDL.Float64,
    'power' : IDL.Nat,
    'topSpeed' : IDL.Nat,
    'engine' : IDL.Text,
  });
  const Vehicle = IDL.Record({
    'id' : IDL.Nat,
    'vehicleType' : IDL.Text,
    'make' : IDL.Text,
    'specs' : Specs,
    'nanosecondsCreated' : IDL.Int,
    'price' : IDL.Int,
    'images' : IDL.Vec(IDL.Text),
  });
  
  return IDL.Service({
    'addVehicle' : IDL.Func(
        [IDL.Text, IDL.Text, Specs, IDL.Int, IDL.Vec(IDL.Text)],
        [IDL.Nat],
        [],
      ),
    'getAllVehicles' : IDL.Func([], [IDL.Vec(Vehicle)], ['query']),
    'getMapSizes' : IDL.Func([], [IDL.Nat, IDL.Nat], ['query']),
    'getUserFavorites' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Nat)],
        ['query'],
      ),
    'getVehicleById' : IDL.Func([IDL.Nat], [Vehicle], ['query']),
    'getVehiclesByType' : IDL.Func([IDL.Text], [IDL.Vec(Vehicle)], ['query']),
    'isFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'isRegistered' : IDL.Func([], [IDL.Bool], ['query']),
    'toggleFavorite' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };